const currencies = [
    { code: "USD", symbol: "$", country: "United States" },
    { code: "AED", symbol: "د.إ", country: "United Arab Emirates" },
    { code: "AFN", symbol: "؋", country: "Afghanistan" },
    { code: "ALL", symbol: "L", country: "Albania" },
    { code: "AMD", symbol: "֏", country: "Armenia" },
    { code: "ARS", symbol: "$", country: "Argentina" },
    { code: "AUD", symbol: "$", country: "Australia" },
    { code: "BAM", symbol: "KM", country: "Bosnia and Herzegovina" },
    { code: "BBD", symbol: "$", country: "Barbados" },
    { code: "BDT", symbol: "৳", country: "Bangladesh" },
    { code: "BGN", symbol: "лв", country: "Bulgaria" },
    { code: "BHD", symbol: ".د.ب", country: "Bahrain" },
    { code: "BMD", symbol: "$", country: "Bermuda" },
    { code: "BRL", symbol: "R$", country: "Brazil" },
    { code: "CAD", symbol: "$", country: "Canada" },
    { code: "CHF", symbol: "CHF", country: "Switzerland" },
    { code: "CNY", symbol: "¥", country: "China" },
    { code: "COP", symbol: "$", country: "Colombia" },
    { code: "CRC", symbol: "₡", country: "Costa Rica" },
    { code: "CVE", symbol: "$", country: "Cape Verde" },
    { code: "CZK", symbol: "Kč", country: "Czech Republic" },
    { code: "DKK", symbol: "kr", country: "Denmark" },
    { code: "DZD", symbol: "دج", country: "Algeria" },
    { code: "EGP", symbol: "£", country: "Egypt" },
    { code: "EUR", symbol: "€", country: "European Union" },
    { code: "GBP", symbol: "£", country: "United Kingdom" },
    { code: "GHS", symbol: "₵", country: "Ghana" },
    { code: "HKD", symbol: "$", country: "Hong Kong" },
    { code: "INR", symbol: "₹", country: "India" },
    { code: "JPY", symbol: "¥", country: "Japan" },
    { code: "KES", symbol: "Sh", country: "Kenya" },
    { code: "KRW", symbol: "₩", country: "South Korea" },
    { code: "MXN", symbol: "$", country: "Mexico" },
    { code: "MYR", symbol: "RM", country: "Malaysia" },
    { code: "NAD", symbol: "$", country: "Namibia" },
    { code: "NGN", symbol: "₦", country: "Nigeria" },
    { code: "NOK", symbol: "kr", country: "Norway" },
    { code: "NZD", symbol: "$", country: "New Zealand" },
    { code: "PAB", symbol: "B/.", country: "Panama" },
    { code: "PHP", symbol: "₱", country: "Philippines" },
    { code: "PKR", symbol: "₨", country: "Pakistan" },
    { code: "PLN", symbol: "zł", country: "Poland" },
    { code: "QAR", symbol: "ر.ق", country: "Qatar" },
    { code: "RON", symbol: "lei", country: "Romania" },
    { code: "RUB", symbol: "₽", country: "Russia" },
    { code: "SAR", symbol: "ر.س", country: "Saudi Arabia" },
    { code: "SEK", symbol: "kr", country: "Sweden" },
    { code: "SGD", symbol: "$", country: "Singapore" },
    { code: "THB", symbol: "฿", country: "Thailand" },
    { code: "TRY", symbol: "₺", country: "Turkey" },
    { code: "TWD", symbol: "NT$", country: "Taiwan" },
    { code: "UAH", symbol: "₴", country: "Ukraine" },
    { code: "VND", symbol: "₫", country: "Vietnam" },
    { code: "ZAR", symbol: "R", country: "South Africa" },
    { code: "ZMW", symbol: "ZK", country: "Zambia" }
  ];
  

export default currencies;